name: Ruff

on:
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Ruff Check
        uses: astral-sh/ruff-action@v3
        with:
          version-file: "pyproject.toml"

      - name: Run Ruff format check
        run: ruff format --check
