name: Ruff

on: [push, pull_request, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3
        with:
          version-file: "pyproject.toml"
          args: "--version"
      - run: ruff check --fix --select I
      - run: ruff format
